# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import adapter_interface_pb2 as adapter__interface__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in adapter_interface_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CloudAdapterStub(object):
    """=============================================================================
    SERVICE DEFINITION
    =============================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/adapter.CloudAdapter/GetStatus',
                request_serializer=adapter__interface__pb2.StatusRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetAvailableServices = channel.unary_unary(
                '/adapter.CloudAdapter/GetAvailableServices',
                request_serializer=adapter__interface__pb2.GetAvailableServicesRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.GetAvailableServicesResponse.FromString,
                _registered_method=True)
        self.GroupExists = channel.unary_unary(
                '/adapter.CloudAdapter/GroupExists',
                request_serializer=adapter__interface__pb2.GroupExistsRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.GroupExistsResponse.FromString,
                _registered_method=True)
        self.CreateGroupWithLeaders = channel.unary_unary(
                '/adapter.CloudAdapter/CreateGroupWithLeaders',
                request_serializer=adapter__interface__pb2.CreateGroupWithLeadersRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.GroupCreatedResponse.FromString,
                _registered_method=True)
        self.AddLeaderToGroup = channel.unary_unary(
                '/adapter.CloudAdapter/AddLeaderToGroup',
                request_serializer=adapter__interface__pb2.AddLeaderToGroupRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.AddLeaderToGroupResponse.FromString,
                _registered_method=True)
        self.CreateUsersForGroup = channel.unary_unary(
                '/adapter.CloudAdapter/CreateUsersForGroup',
                request_serializer=adapter__interface__pb2.CreateUsersForGroupRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.CreateUsersForGroupResponse.FromString,
                _registered_method=True)
        self.AssignPolicies = channel.unary_unary(
                '/adapter.CloudAdapter/AssignPolicies',
                request_serializer=adapter__interface__pb2.AssignPoliciesRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.AssignPoliciesResponse.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/adapter.CloudAdapter/DeleteUser',
                request_serializer=adapter__interface__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.DeleteUserResponse.FromString,
                _registered_method=True)
        self.RemoveGroup = channel.unary_unary(
                '/adapter.CloudAdapter/RemoveGroup',
                request_serializer=adapter__interface__pb2.RemoveGroupRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.RemoveGroupResponse.FromString,
                _registered_method=True)
        self.GetGroupResourcesList = channel.unary_unary(
                '/adapter.CloudAdapter/GetGroupResourcesList',
                request_serializer=adapter__interface__pb2.GetGroupResourcesListRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.GetGroupResourcesListResponse.FromString,
                _registered_method=True)
        self.GetResourceCount = channel.unary_unary(
                '/adapter.CloudAdapter/GetResourceCount',
                request_serializer=adapter__interface__pb2.ResourceCountRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.ResourceCountResponse.FromString,
                _registered_method=True)
        self.DeleteResource = channel.unary_unary(
                '/adapter.CloudAdapter/DeleteResource',
                request_serializer=adapter__interface__pb2.DeleteResourceRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.DeleteResourceResponse.FromString,
                _registered_method=True)
        self.CleanupGroupResources = channel.unary_unary(
                '/adapter.CloudAdapter/CleanupGroupResources',
                request_serializer=adapter__interface__pb2.CleanupGroupRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.CleanupGroupResponse.FromString,
                _registered_method=True)
        self.GetTotalCost = channel.unary_unary(
                '/adapter.CloudAdapter/GetTotalCost',
                request_serializer=adapter__interface__pb2.CostRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.CostResponse.FromString,
                _registered_method=True)
        self.GetTotalCostsForAllGroups = channel.unary_unary(
                '/adapter.CloudAdapter/GetTotalCostsForAllGroups',
                request_serializer=adapter__interface__pb2.CostRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.AllGroupsCostResponse.FromString,
                _registered_method=True)
        self.GetTotalCostForGroup = channel.unary_unary(
                '/adapter.CloudAdapter/GetTotalCostForGroup',
                request_serializer=adapter__interface__pb2.CostRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.CostResponse.FromString,
                _registered_method=True)
        self.GetGroupCostWithServiceBreakdown = channel.unary_unary(
                '/adapter.CloudAdapter/GetGroupCostWithServiceBreakdown',
                request_serializer=adapter__interface__pb2.GroupServiceBreakdownRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.GroupServiceBreakdownResponse.FromString,
                _registered_method=True)
        self.GetGroupCostsLast6MonthsByService = channel.unary_unary(
                '/adapter.CloudAdapter/GetGroupCostsLast6MonthsByService',
                request_serializer=adapter__interface__pb2.GroupLast6MonthsCostRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.GroupCostMapResponse.FromString,
                _registered_method=True)
        self.GetGroupMonthlyCostsLast6Months = channel.unary_unary(
                '/adapter.CloudAdapter/GetGroupMonthlyCostsLast6Months',
                request_serializer=adapter__interface__pb2.GroupLast6MonthsCostRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.GroupMonthlyCostsResponse.FromString,
                _registered_method=True)


class CloudAdapterServicer(object):
    """=============================================================================
    SERVICE DEFINITION
    =============================================================================
    """

    def GetStatus(self, request, context):
        """--- Section 1: Health & Configuration ---
        Checks if the system (AWS/Local) is operational and lists available services
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableServices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GroupExists(self, request, context):
        """--- Section 2: Identity Management (Groups, Users, Policies) ---
        Group creation, adding users/leaders, assigning policies, and account deletion
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateGroupWithLeaders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddLeaderToGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUsersForGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignPolicies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroupResourcesList(self, request, context):
        """--- Section 3: Resource Management ---
        Resource management: listing, counting, and cleanup
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResourceCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CleanupGroupResources(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTotalCost(self, request, context):
        """--- Section 4: Cost Monitoring ---
        Cost reports: global, per group, historical trends, and service breakdowns
        Global AWS Cost
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTotalCostsForAllGroups(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTotalCostForGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroupCostWithServiceBreakdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroupCostsLast6MonthsByService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroupMonthlyCostsLast6Months(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CloudAdapterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=adapter__interface__pb2.StatusRequest.FromString,
                    response_serializer=adapter__interface__pb2.StatusResponse.SerializeToString,
            ),
            'GetAvailableServices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableServices,
                    request_deserializer=adapter__interface__pb2.GetAvailableServicesRequest.FromString,
                    response_serializer=adapter__interface__pb2.GetAvailableServicesResponse.SerializeToString,
            ),
            'GroupExists': grpc.unary_unary_rpc_method_handler(
                    servicer.GroupExists,
                    request_deserializer=adapter__interface__pb2.GroupExistsRequest.FromString,
                    response_serializer=adapter__interface__pb2.GroupExistsResponse.SerializeToString,
            ),
            'CreateGroupWithLeaders': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGroupWithLeaders,
                    request_deserializer=adapter__interface__pb2.CreateGroupWithLeadersRequest.FromString,
                    response_serializer=adapter__interface__pb2.GroupCreatedResponse.SerializeToString,
            ),
            'AddLeaderToGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.AddLeaderToGroup,
                    request_deserializer=adapter__interface__pb2.AddLeaderToGroupRequest.FromString,
                    response_serializer=adapter__interface__pb2.AddLeaderToGroupResponse.SerializeToString,
            ),
            'CreateUsersForGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUsersForGroup,
                    request_deserializer=adapter__interface__pb2.CreateUsersForGroupRequest.FromString,
                    response_serializer=adapter__interface__pb2.CreateUsersForGroupResponse.SerializeToString,
            ),
            'AssignPolicies': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignPolicies,
                    request_deserializer=adapter__interface__pb2.AssignPoliciesRequest.FromString,
                    response_serializer=adapter__interface__pb2.AssignPoliciesResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=adapter__interface__pb2.DeleteUserRequest.FromString,
                    response_serializer=adapter__interface__pb2.DeleteUserResponse.SerializeToString,
            ),
            'RemoveGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveGroup,
                    request_deserializer=adapter__interface__pb2.RemoveGroupRequest.FromString,
                    response_serializer=adapter__interface__pb2.RemoveGroupResponse.SerializeToString,
            ),
            'GetGroupResourcesList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroupResourcesList,
                    request_deserializer=adapter__interface__pb2.GetGroupResourcesListRequest.FromString,
                    response_serializer=adapter__interface__pb2.GetGroupResourcesListResponse.SerializeToString,
            ),
            'GetResourceCount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResourceCount,
                    request_deserializer=adapter__interface__pb2.ResourceCountRequest.FromString,
                    response_serializer=adapter__interface__pb2.ResourceCountResponse.SerializeToString,
            ),
            'DeleteResource': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteResource,
                    request_deserializer=adapter__interface__pb2.DeleteResourceRequest.FromString,
                    response_serializer=adapter__interface__pb2.DeleteResourceResponse.SerializeToString,
            ),
            'CleanupGroupResources': grpc.unary_unary_rpc_method_handler(
                    servicer.CleanupGroupResources,
                    request_deserializer=adapter__interface__pb2.CleanupGroupRequest.FromString,
                    response_serializer=adapter__interface__pb2.CleanupGroupResponse.SerializeToString,
            ),
            'GetTotalCost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTotalCost,
                    request_deserializer=adapter__interface__pb2.CostRequest.FromString,
                    response_serializer=adapter__interface__pb2.CostResponse.SerializeToString,
            ),
            'GetTotalCostsForAllGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTotalCostsForAllGroups,
                    request_deserializer=adapter__interface__pb2.CostRequest.FromString,
                    response_serializer=adapter__interface__pb2.AllGroupsCostResponse.SerializeToString,
            ),
            'GetTotalCostForGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTotalCostForGroup,
                    request_deserializer=adapter__interface__pb2.CostRequest.FromString,
                    response_serializer=adapter__interface__pb2.CostResponse.SerializeToString,
            ),
            'GetGroupCostWithServiceBreakdown': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroupCostWithServiceBreakdown,
                    request_deserializer=adapter__interface__pb2.GroupServiceBreakdownRequest.FromString,
                    response_serializer=adapter__interface__pb2.GroupServiceBreakdownResponse.SerializeToString,
            ),
            'GetGroupCostsLast6MonthsByService': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroupCostsLast6MonthsByService,
                    request_deserializer=adapter__interface__pb2.GroupLast6MonthsCostRequest.FromString,
                    response_serializer=adapter__interface__pb2.GroupCostMapResponse.SerializeToString,
            ),
            'GetGroupMonthlyCostsLast6Months': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroupMonthlyCostsLast6Months,
                    request_deserializer=adapter__interface__pb2.GroupLast6MonthsCostRequest.FromString,
                    response_serializer=adapter__interface__pb2.GroupMonthlyCostsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'adapter.CloudAdapter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('adapter.CloudAdapter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CloudAdapter(object):
    """=============================================================================
    SERVICE DEFINITION
    =============================================================================
    """

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adapter.CloudAdapter/GetStatus',
            adapter__interface__pb2.StatusRequest.SerializeToString,
            adapter__interface__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvailableServices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adapter.CloudAdapter/GetAvailableServices',
            adapter__interface__pb2.GetAvailableServicesRequest.SerializeToString,
            adapter__interface__pb2.GetAvailableServicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GroupExists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adapter.CloudAdapter/GroupExists',
            adapter__interface__pb2.GroupExistsRequest.SerializeToString,
            adapter__interface__pb2.GroupExistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateGroupWithLeaders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adapter.CloudAdapter/CreateGroupWithLeaders',
            adapter__interface__pb2.CreateGroupWithLeadersRequest.SerializeToString,
            adapter__interface__pb2.GroupCreatedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddLeaderToGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adapter.CloudAdapter/AddLeaderToGroup',
            adapter__interface__pb2.AddLeaderToGroupRequest.SerializeToString,
            adapter__interface__pb2.AddLeaderToGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUsersForGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adapter.CloudAdapter/CreateUsersForGroup',
            adapter__interface__pb2.CreateUsersForGroupRequest.SerializeToString,
            adapter__interface__pb2.CreateUsersForGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignPolicies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adapter.CloudAdapter/AssignPolicies',
            adapter__interface__pb2.AssignPoliciesRequest.SerializeToString,
            adapter__interface__pb2.AssignPoliciesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adapter.CloudAdapter/DeleteUser',
            adapter__interface__pb2.DeleteUserRequest.SerializeToString,
            adapter__interface__pb2.DeleteUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adapter.CloudAdapter/RemoveGroup',
            adapter__interface__pb2.RemoveGroupRequest.SerializeToString,
            adapter__interface__pb2.RemoveGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGroupResourcesList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adapter.CloudAdapter/GetGroupResourcesList',
            adapter__interface__pb2.GetGroupResourcesListRequest.SerializeToString,
            adapter__interface__pb2.GetGroupResourcesListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResourceCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adapter.CloudAdapter/GetResourceCount',
            adapter__interface__pb2.ResourceCountRequest.SerializeToString,
            adapter__interface__pb2.ResourceCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adapter.CloudAdapter/DeleteResource',
            adapter__interface__pb2.DeleteResourceRequest.SerializeToString,
            adapter__interface__pb2.DeleteResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CleanupGroupResources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adapter.CloudAdapter/CleanupGroupResources',
            adapter__interface__pb2.CleanupGroupRequest.SerializeToString,
            adapter__interface__pb2.CleanupGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTotalCost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adapter.CloudAdapter/GetTotalCost',
            adapter__interface__pb2.CostRequest.SerializeToString,
            adapter__interface__pb2.CostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTotalCostsForAllGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adapter.CloudAdapter/GetTotalCostsForAllGroups',
            adapter__interface__pb2.CostRequest.SerializeToString,
            adapter__interface__pb2.AllGroupsCostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTotalCostForGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adapter.CloudAdapter/GetTotalCostForGroup',
            adapter__interface__pb2.CostRequest.SerializeToString,
            adapter__interface__pb2.CostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGroupCostWithServiceBreakdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adapter.CloudAdapter/GetGroupCostWithServiceBreakdown',
            adapter__interface__pb2.GroupServiceBreakdownRequest.SerializeToString,
            adapter__interface__pb2.GroupServiceBreakdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGroupCostsLast6MonthsByService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adapter.CloudAdapter/GetGroupCostsLast6MonthsByService',
            adapter__interface__pb2.GroupLast6MonthsCostRequest.SerializeToString,
            adapter__interface__pb2.GroupCostMapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGroupMonthlyCostsLast6Months(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/adapter.CloudAdapter/GetGroupMonthlyCostsLast6Months',
            adapter__interface__pb2.GroupLast6MonthsCostRequest.SerializeToString,
            adapter__interface__pb2.GroupMonthlyCostsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
