# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import adapter_interface_pb2 as adapter__interface__pb2


class CloudAdapterStub(object):
    """=== CloudAdapter Service Definition ===
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/adapter.CloudAdapter/GetStatus',
                request_serializer=adapter__interface__pb2.StatusRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.StatusResponse.FromString,
                )
        self.GetAvailableServices = channel.unary_unary(
                '/adapter.CloudAdapter/GetAvailableServices',
                request_serializer=adapter__interface__pb2.GetAvailableServicesRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.GetAvailableServicesResponse.FromString,
                )
        self.CreateGroupWithLeaders = channel.unary_unary(
                '/adapter.CloudAdapter/CreateGroupWithLeaders',
                request_serializer=adapter__interface__pb2.CreateGroupWithLeadersRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.GroupCreatedResponse.FromString,
                )
        self.CreateUsersForGroup = channel.unary_unary(
                '/adapter.CloudAdapter/CreateUsersForGroup',
                request_serializer=adapter__interface__pb2.CreateUsersForGroupRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.CreateUsersForGroupResponse.FromString,
                )
        self.GroupExists = channel.unary_unary(
                '/adapter.CloudAdapter/GroupExists',
                request_serializer=adapter__interface__pb2.GroupExistsRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.GroupExistsResponse.FromString,
                )
        self.GetResourceCount = channel.unary_unary(
                '/adapter.CloudAdapter/GetResourceCount',
                request_serializer=adapter__interface__pb2.ResourceCountRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.ResourceCountResponse.FromString,
                )
        self.GetTotalCostForGroup = channel.unary_unary(
                '/adapter.CloudAdapter/GetTotalCostForGroup',
                request_serializer=adapter__interface__pb2.CostRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.CostResponse.FromString,
                )
        self.GetTotalCostsForAllGroups = channel.unary_unary(
                '/adapter.CloudAdapter/GetTotalCostsForAllGroups',
                request_serializer=adapter__interface__pb2.CostRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.AllGroupsCostResponse.FromString,
                )
        self.GetTotalCost = channel.unary_unary(
                '/adapter.CloudAdapter/GetTotalCost',
                request_serializer=adapter__interface__pb2.CostRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.CostResponse.FromString,
                )
        self.GetGroupCostWithServiceBreakdown = channel.unary_unary(
                '/adapter.CloudAdapter/GetGroupCostWithServiceBreakdown',
                request_serializer=adapter__interface__pb2.GroupServiceBreakdownRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.GroupServiceBreakdownResponse.FromString,
                )
        self.GetTotalCostWithServiceBreakdown = channel.unary_unary(
                '/adapter.CloudAdapter/GetTotalCostWithServiceBreakdown',
                request_serializer=adapter__interface__pb2.CostRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.GroupServiceBreakdownResponse.FromString,
                )
        self.GetGroupCostsLast6MonthsByService = channel.unary_unary(
                '/adapter.CloudAdapter/GetGroupCostsLast6MonthsByService',
                request_serializer=adapter__interface__pb2.GroupCostMapRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.GroupCostMapResponse.FromString,
                )
        self.GetGroupMonthlyCostsLast6Months = channel.unary_unary(
                '/adapter.CloudAdapter/GetGroupMonthlyCostsLast6Months',
                request_serializer=adapter__interface__pb2.GroupMonthlyCostsRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.GroupMonthlyCostsResponse.FromString,
                )
        self.RemoveGroup = channel.unary_unary(
                '/adapter.CloudAdapter/RemoveGroup',
                request_serializer=adapter__interface__pb2.RemoveGroupRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.RemoveGroupResponse.FromString,
                )
        self.CleanupGroupResources = channel.unary_unary(
                '/adapter.CloudAdapter/CleanupGroupResources',
                request_serializer=adapter__interface__pb2.CleanupGroupRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.CleanupGroupResponse.FromString,
                )


class CloudAdapterServicer(object):
    """=== CloudAdapter Service Definition ===
    """

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableServices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateGroupWithLeaders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUsersForGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GroupExists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResourceCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTotalCostForGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTotalCostsForAllGroups(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTotalCost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroupCostWithServiceBreakdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTotalCostWithServiceBreakdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroupCostsLast6MonthsByService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroupMonthlyCostsLast6Months(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CleanupGroupResources(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CloudAdapterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=adapter__interface__pb2.StatusRequest.FromString,
                    response_serializer=adapter__interface__pb2.StatusResponse.SerializeToString,
            ),
            'GetAvailableServices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableServices,
                    request_deserializer=adapter__interface__pb2.GetAvailableServicesRequest.FromString,
                    response_serializer=adapter__interface__pb2.GetAvailableServicesResponse.SerializeToString,
            ),
            'CreateGroupWithLeaders': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGroupWithLeaders,
                    request_deserializer=adapter__interface__pb2.CreateGroupWithLeadersRequest.FromString,
                    response_serializer=adapter__interface__pb2.GroupCreatedResponse.SerializeToString,
            ),
            'CreateUsersForGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUsersForGroup,
                    request_deserializer=adapter__interface__pb2.CreateUsersForGroupRequest.FromString,
                    response_serializer=adapter__interface__pb2.CreateUsersForGroupResponse.SerializeToString,
            ),
            'GroupExists': grpc.unary_unary_rpc_method_handler(
                    servicer.GroupExists,
                    request_deserializer=adapter__interface__pb2.GroupExistsRequest.FromString,
                    response_serializer=adapter__interface__pb2.GroupExistsResponse.SerializeToString,
            ),
            'GetResourceCount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResourceCount,
                    request_deserializer=adapter__interface__pb2.ResourceCountRequest.FromString,
                    response_serializer=adapter__interface__pb2.ResourceCountResponse.SerializeToString,
            ),
            'GetTotalCostForGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTotalCostForGroup,
                    request_deserializer=adapter__interface__pb2.CostRequest.FromString,
                    response_serializer=adapter__interface__pb2.CostResponse.SerializeToString,
            ),
            'GetTotalCostsForAllGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTotalCostsForAllGroups,
                    request_deserializer=adapter__interface__pb2.CostRequest.FromString,
                    response_serializer=adapter__interface__pb2.AllGroupsCostResponse.SerializeToString,
            ),
            'GetTotalCost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTotalCost,
                    request_deserializer=adapter__interface__pb2.CostRequest.FromString,
                    response_serializer=adapter__interface__pb2.CostResponse.SerializeToString,
            ),
            'GetGroupCostWithServiceBreakdown': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroupCostWithServiceBreakdown,
                    request_deserializer=adapter__interface__pb2.GroupServiceBreakdownRequest.FromString,
                    response_serializer=adapter__interface__pb2.GroupServiceBreakdownResponse.SerializeToString,
            ),
            'GetTotalCostWithServiceBreakdown': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTotalCostWithServiceBreakdown,
                    request_deserializer=adapter__interface__pb2.CostRequest.FromString,
                    response_serializer=adapter__interface__pb2.GroupServiceBreakdownResponse.SerializeToString,
            ),
            'GetGroupCostsLast6MonthsByService': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroupCostsLast6MonthsByService,
                    request_deserializer=adapter__interface__pb2.GroupCostMapRequest.FromString,
                    response_serializer=adapter__interface__pb2.GroupCostMapResponse.SerializeToString,
            ),
            'GetGroupMonthlyCostsLast6Months': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroupMonthlyCostsLast6Months,
                    request_deserializer=adapter__interface__pb2.GroupMonthlyCostsRequest.FromString,
                    response_serializer=adapter__interface__pb2.GroupMonthlyCostsResponse.SerializeToString,
            ),
            'RemoveGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveGroup,
                    request_deserializer=adapter__interface__pb2.RemoveGroupRequest.FromString,
                    response_serializer=adapter__interface__pb2.RemoveGroupResponse.SerializeToString,
            ),
            'CleanupGroupResources': grpc.unary_unary_rpc_method_handler(
                    servicer.CleanupGroupResources,
                    request_deserializer=adapter__interface__pb2.CleanupGroupRequest.FromString,
                    response_serializer=adapter__interface__pb2.CleanupGroupResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'adapter.CloudAdapter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CloudAdapter(object):
    """=== CloudAdapter Service Definition ===
    """

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/adapter.CloudAdapter/GetStatus',
            adapter__interface__pb2.StatusRequest.SerializeToString,
            adapter__interface__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAvailableServices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/adapter.CloudAdapter/GetAvailableServices',
            adapter__interface__pb2.GetAvailableServicesRequest.SerializeToString,
            adapter__interface__pb2.GetAvailableServicesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateGroupWithLeaders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/adapter.CloudAdapter/CreateGroupWithLeaders',
            adapter__interface__pb2.CreateGroupWithLeadersRequest.SerializeToString,
            adapter__interface__pb2.GroupCreatedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateUsersForGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/adapter.CloudAdapter/CreateUsersForGroup',
            adapter__interface__pb2.CreateUsersForGroupRequest.SerializeToString,
            adapter__interface__pb2.CreateUsersForGroupResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GroupExists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/adapter.CloudAdapter/GroupExists',
            adapter__interface__pb2.GroupExistsRequest.SerializeToString,
            adapter__interface__pb2.GroupExistsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetResourceCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/adapter.CloudAdapter/GetResourceCount',
            adapter__interface__pb2.ResourceCountRequest.SerializeToString,
            adapter__interface__pb2.ResourceCountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTotalCostForGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/adapter.CloudAdapter/GetTotalCostForGroup',
            adapter__interface__pb2.CostRequest.SerializeToString,
            adapter__interface__pb2.CostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTotalCostsForAllGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/adapter.CloudAdapter/GetTotalCostsForAllGroups',
            adapter__interface__pb2.CostRequest.SerializeToString,
            adapter__interface__pb2.AllGroupsCostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTotalCost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/adapter.CloudAdapter/GetTotalCost',
            adapter__interface__pb2.CostRequest.SerializeToString,
            adapter__interface__pb2.CostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGroupCostWithServiceBreakdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/adapter.CloudAdapter/GetGroupCostWithServiceBreakdown',
            adapter__interface__pb2.GroupServiceBreakdownRequest.SerializeToString,
            adapter__interface__pb2.GroupServiceBreakdownResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTotalCostWithServiceBreakdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/adapter.CloudAdapter/GetTotalCostWithServiceBreakdown',
            adapter__interface__pb2.CostRequest.SerializeToString,
            adapter__interface__pb2.GroupServiceBreakdownResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGroupCostsLast6MonthsByService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/adapter.CloudAdapter/GetGroupCostsLast6MonthsByService',
            adapter__interface__pb2.GroupCostMapRequest.SerializeToString,
            adapter__interface__pb2.GroupCostMapResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGroupMonthlyCostsLast6Months(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/adapter.CloudAdapter/GetGroupMonthlyCostsLast6Months',
            adapter__interface__pb2.GroupMonthlyCostsRequest.SerializeToString,
            adapter__interface__pb2.GroupMonthlyCostsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/adapter.CloudAdapter/RemoveGroup',
            adapter__interface__pb2.RemoveGroupRequest.SerializeToString,
            adapter__interface__pb2.RemoveGroupResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CleanupGroupResources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/adapter.CloudAdapter/CleanupGroupResources',
            adapter__interface__pb2.CleanupGroupRequest.SerializeToString,
            adapter__interface__pb2.CleanupGroupResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
