# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import adapter_interface_pb2 as adapter__interface__pb2


class CloudAdapterStub(object):
    """=== CloudAdapter Service Definition ===
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/adapter.CloudAdapter/GetStatus',
                request_serializer=adapter__interface__pb2.StatusRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.StatusResponse.FromString,
                )
        self.CreateGroupWithLeaders = channel.unary_unary(
                '/adapter.CloudAdapter/CreateGroupWithLeaders',
                request_serializer=adapter__interface__pb2.CreateGroupWithLeadersRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.GroupCreatedResponse.FromString,
                )
        self.CreateUsersForGroup = channel.unary_unary(
                '/adapter.CloudAdapter/CreateUsersForGroup',
                request_serializer=adapter__interface__pb2.CreateUsersForGroupRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.CreateUsersForGroupResponse.FromString,
                )
        self.GroupExists = channel.unary_unary(
                '/adapter.CloudAdapter/GroupExists',
                request_serializer=adapter__interface__pb2.GroupExistsRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.GroupExistsResponse.FromString,
                )
        self.GetTotalCostForGroup = channel.unary_unary(
                '/adapter.CloudAdapter/GetTotalCostForGroup',
                request_serializer=adapter__interface__pb2.CostRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.CostResponse.FromString,
                )
        self.GetTotalCostsForAllGroups = channel.unary_unary(
                '/adapter.CloudAdapter/GetTotalCostsForAllGroups',
                request_serializer=adapter__interface__pb2.CostRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.AllGroupsCostResponse.FromString,
                )
        self.GetTotalCost = channel.unary_unary(
                '/adapter.CloudAdapter/GetTotalCost',
                request_serializer=adapter__interface__pb2.CostRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.CostResponse.FromString,
                )
        self.GetGroupCostWithServiceBreakdown = channel.unary_unary(
                '/adapter.CloudAdapter/GetGroupCostWithServiceBreakdown',
                request_serializer=adapter__interface__pb2.GroupServiceBreakdownRequest.SerializeToString,
                response_deserializer=adapter__interface__pb2.GroupServiceBreakdownResponse.FromString,
                )


class CloudAdapterServicer(object):
    """=== CloudAdapter Service Definition ===
    """

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateGroupWithLeaders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUsersForGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GroupExists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTotalCostForGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTotalCostsForAllGroups(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTotalCost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroupCostWithServiceBreakdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CloudAdapterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=adapter__interface__pb2.StatusRequest.FromString,
                    response_serializer=adapter__interface__pb2.StatusResponse.SerializeToString,
            ),
            'CreateGroupWithLeaders': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGroupWithLeaders,
                    request_deserializer=adapter__interface__pb2.CreateGroupWithLeadersRequest.FromString,
                    response_serializer=adapter__interface__pb2.GroupCreatedResponse.SerializeToString,
            ),
            'CreateUsersForGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUsersForGroup,
                    request_deserializer=adapter__interface__pb2.CreateUsersForGroupRequest.FromString,
                    response_serializer=adapter__interface__pb2.CreateUsersForGroupResponse.SerializeToString,
            ),
            'GroupExists': grpc.unary_unary_rpc_method_handler(
                    servicer.GroupExists,
                    request_deserializer=adapter__interface__pb2.GroupExistsRequest.FromString,
                    response_serializer=adapter__interface__pb2.GroupExistsResponse.SerializeToString,
            ),
            'GetTotalCostForGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTotalCostForGroup,
                    request_deserializer=adapter__interface__pb2.CostRequest.FromString,
                    response_serializer=adapter__interface__pb2.CostResponse.SerializeToString,
            ),
            'GetTotalCostsForAllGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTotalCostsForAllGroups,
                    request_deserializer=adapter__interface__pb2.CostRequest.FromString,
                    response_serializer=adapter__interface__pb2.AllGroupsCostResponse.SerializeToString,
            ),
            'GetTotalCost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTotalCost,
                    request_deserializer=adapter__interface__pb2.CostRequest.FromString,
                    response_serializer=adapter__interface__pb2.CostResponse.SerializeToString,
            ),
            'GetGroupCostWithServiceBreakdown': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroupCostWithServiceBreakdown,
                    request_deserializer=adapter__interface__pb2.GroupServiceBreakdownRequest.FromString,
                    response_serializer=adapter__interface__pb2.GroupServiceBreakdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'adapter.CloudAdapter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CloudAdapter(object):
    """=== CloudAdapter Service Definition ===
    """

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/adapter.CloudAdapter/GetStatus',
            adapter__interface__pb2.StatusRequest.SerializeToString,
            adapter__interface__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateGroupWithLeaders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/adapter.CloudAdapter/CreateGroupWithLeaders',
            adapter__interface__pb2.CreateGroupWithLeadersRequest.SerializeToString,
            adapter__interface__pb2.GroupCreatedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateUsersForGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/adapter.CloudAdapter/CreateUsersForGroup',
            adapter__interface__pb2.CreateUsersForGroupRequest.SerializeToString,
            adapter__interface__pb2.CreateUsersForGroupResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GroupExists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/adapter.CloudAdapter/GroupExists',
            adapter__interface__pb2.GroupExistsRequest.SerializeToString,
            adapter__interface__pb2.GroupExistsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTotalCostForGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/adapter.CloudAdapter/GetTotalCostForGroup',
            adapter__interface__pb2.CostRequest.SerializeToString,
            adapter__interface__pb2.CostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTotalCostsForAllGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/adapter.CloudAdapter/GetTotalCostsForAllGroups',
            adapter__interface__pb2.CostRequest.SerializeToString,
            adapter__interface__pb2.AllGroupsCostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTotalCost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/adapter.CloudAdapter/GetTotalCost',
            adapter__interface__pb2.CostRequest.SerializeToString,
            adapter__interface__pb2.CostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGroupCostWithServiceBreakdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/adapter.CloudAdapter/GetGroupCostWithServiceBreakdown',
            adapter__interface__pb2.GroupServiceBreakdownRequest.SerializeToString,
            adapter__interface__pb2.GroupServiceBreakdownResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
